   #  Source: https://en.wikipedia.org/wiki/List_of_law_enforcement_agencies_in_Vermont
   LAW_AGENCIES = [ "Addison County Sheriff's Office", "Barre Police Department",
     "Bellows Falls Police Department", "Bennington County Sheriff's Department",
     "Bennington Police Department", "Brandon Police Department",
     "Brattleboro Police Department", "Bristol Police Department",
     "Burlington Police Department", "Caledonia County Sheriff's Office",
     "Castleton Police Department", "Chittenden County Sheriff's Department",
     "Colchester Police Department", "Dover Police Department",
     "Essex County Sheriff's Office", "Essex Police Department",
     "Fair Haven Police Department", "Franklin County Sheriff's Department",
     "Grand Isle County Sheriff's Office", "Hardwick-Greensboro Police Department",
     "Hartford Police Department", "Lamoille County Sheriff's Department",
     "Ludlow Police Department", "Lyndonville Police Department",
     "Manchester Police Department", "Middlebury Police Department",
     "Milton Police Department", "Montpelier Police Department",
     "Morristown Police Department", "Newport Police Department",
     "Northfield Police Department", "Norwich Police Department",
     "Orange County Sheriff's Department", "Orleans County Sheriff's Office", "Randolph Police Department",
     "Rutland County Sheriff's Office", "Rutland Police Department",
     "South Burlington Police Department", "Springfield Police Department",
     "St. Albans City Police Department", "St. Johnsbury Police Department",
     "Stowe Police Department", "Swanton Village Police Department",
     "Thetford Police Department", "Vergennes Police Department",
     "Vermont Capitol Police", "Vermont Department of Corrections",
     "Vermont Department of Motor Vehicles Law Enforcement", "Vermont Department of Public Safety",
     "Vermont Fish and Wildlife Department", "Vermont Game Wardens",
     "Vermont Secretary of State, Investigation Division", "Vermont State Police",
     "Washington County Sheriff's Office", "Waterbury Police Department",
     "Williston Police Department", "Wilmington Police Department",
     "Windham County Sheriff's Department", "Windsor County Sheriff's Department",
     "Windsor Police Department", "Winhall Police Department", "Winooski Police Department",
     "Woodstock Police Department" ]
